'use client'

import { useEffect, useState } from 'react'
import Image from 'next/image'
import Link from 'next/link'
import { ArrowLeft, BadgeCheck, Building2, CheckCircle2, ExternalLink, FileText, KeyRound, Landmark, ShieldAlert } from 'lucide-react'
import Navigation from '@/components/Navigation'
import Footer from '@/components/Footer'
import PropertySlider from '@/components/PropertySlider'
import InformationalDisclaimer from '@/components/legal/InformationalDisclaimer'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'

const CONTENT = {
  cs: {
    back: 'Všechny články', category: 'Koupě nemovitosti v Itálii', read: '10 minut čtení',
    title: 'Codice fiscale při koupi nemovitosti v Itálii: kompletní návod pro Čechy',
    intro: 'Italský daňový identifikační kód – codice fiscale – je jedním z prvních dokumentů, které by si měl zahraniční kupující obstarat. Vysvětlujeme, co přesně znamená, proč jej potřebujete při koupi domu nebo bytu a jak o něj správně požádat z České republiky nebo přímo v Itálii.',
    imageAlt: 'Ilustrační italská zdravotní karta s prázdnými údaji vedle dokumentů ke koupi domu',
    caption: 'Codice fiscale si vyřiďte včas: údaje v potvrzení musí přesně odpovídat dokladu totožnosti, který použijete při koupi.',
    quickTitle: 'Stručná odpověď',
    quick: 'Bez úředně přiděleného codice fiscale nelze standardně dokončit notářský převod nemovitosti ani navazující daňovou registraci. Samotné hledání domu jej nevyžaduje, ale čekat až na termín rogita je zbytečné riziko. Ideální je požádat ještě před podpisem závazné nabídky nebo předběžné smlouvy.',
    sections: [
      { title: 'Co je codice fiscale – a co není', paragraphs: ['Codice fiscale je osobní alfanumerický identifikátor, který přiděluje Agenzia delle Entrate. Slouží k jednoznačné identifikaci fyzické osoby ve styku s italskými úřady i soukromými subjekty. U fyzických osob má běžně 16 znaků odvozených z osobních údajů, rozhodující je však úřední přidělení, nikoli výsledek internetové kalkulačky.', 'Není to DIČ pro podnikání, povolení k pobytu ani doklad italské daňové rezidence. Není totožný ani se zdravotní kartou: číslo se na ní může objevit, avšak osoba žijící v zahraničí kvůli samotnému přidělení kódu nárok na italskou zdravotní kartu nezískává.'], bullets: ['identifikuje kupujícího v listinách a daňových podáních', 'běžně nemá datum expirace', 'změna bydliště sama o sobě kód nemění', 'každý spolukupující potřebuje vlastní kód'] },
      { title: 'Proč jej kupující nemovitosti potřebuje', paragraphs: ['Při koupi je kód používán notářem a úřady k identifikaci stran, výpočtu a odvodu daní, registraci listin a následným úkonům spojeným s vlastnictvím. Může být požadován také při otevření účtu, žádosti o hypotéku, uzavření smluv na energie nebo při dalších daňových povinnostech.', 'Ne každá nezávazná prohlídka či první jednání jej vyžaduje. U některých soukromých listin existují pro nerezidenty zvláštní administrativní postupy. Pro bezpečné plánování koupě však počítejte s tím, že před finálním notářským aktem musí být kód správně přidělen a údaje musí souhlasit s dokladem totožnosti.'], bullets: ['nabídka a předběžná smlouva: vhodné mít již připravený', 'rogito u notáře: prakticky nezbytný', 'registrace a daně: používá se k přiřazení plateb a listin', 'po koupi: využívá se při dalších smlouvách a povinnostech'] },
      { title: 'Tři oficiální způsoby, jak jej získat', paragraphs: ['Italské orgány uvádějí tři základní cesty. Vyberte ji podle toho, kde bydlíte a jak rychle se blíží podpis.'], steps: [{t:'1. Konzulát v zemi bydliště',d:'Pro osobu s bydlištěm v České republice je nejpohodlnější postup podle aktuálních instrukcí konzulárního oddělení Velvyslanectví Itálie v Praze. Žádost se zasílá s formulářem AA4/8 a přílohami na adresu uvedenou ambasádou.'},{t:'2. Agenzia delle Entrate v Itálii',d:'Při pobytu v Itálii lze požádat přímo územní pracoviště finanční správy. Je nutný formulář AA4/8, platný doklad totožnosti a uvedení důvodu žádosti.'},{t:'3. Zmocněná osoba v Itálii',d:'Žadatel může zvláštní plnou mocí pověřit jinou osobu, aby žádost podala u Agenzia delle Entrate. Zmocněnec předkládá svůj doklad, kopii dokladu žadatele a správně vyplněné zmocnění.'}] },
      { title: 'Postup pro žadatele z České republiky', paragraphs: ['Podle zveřejněných pokynů italského velvyslanectví v Praze má český rezident zaslat konzulárnímu oddělení kompletní žádost. Vždy se řiďte aktuální verzí stránky ambasády, protože kontakty a organizační pravidla se mohou změnit.'], bullets: ['vyplněný a podepsaný formulář AA4/8; údaje přesně podle průkazu', 'kopie platného pasu nebo občanského průkazu s fotografií; řidičský průkaz není akceptován', 'doklad o bydlišti v České republice', 'jasný důvod žádosti, například plánovaná koupě nemovitosti v Itálii', 'kontrola čitelnosti všech příloh před odesláním'], note: 'Ambasáda uvádí, že neúplné žádosti a žádosti osob bez bydliště v České republice odmítne. Pevnou dobu vyřízení neslibuje; požádejte proto s rezervou.' },
      { title: 'Jak správně vyplnit formulář AA4/8', paragraphs: ['Formulář se vyplňuje hůlkovým písmem, musí obsahovat všechny povinné údaje a podpis. Nerezident vyplňuje také zahraniční adresu a uvede důvod žádosti. Jméno, příjmení, datum a místo narození musí odpovídat přiloženému dokladu.', 'Při zastoupení je nutné doplnit a podepsat část o zmocnění. Chyba v osobních údajích se může projevit až při přípravě smlouvy nebo u notáře; oprava pak zdržuje celý obchod. Pražský konzulát zároveň upozorňuje, že opravy již přiděleného kódu řeší Agenzia delle Entrate v Itálii.'], bullets: ['nepřepisujte údaje podle neoficiálního online generátoru', 'nežádejte o nový kód, pokud vám již byl dříve přidělen', 'zkontrolujte shodu s dokladem použitým u notáře', 'uschovejte elektronické potvrzení v originálním PDF'] },
      { title: 'Co obdržíte a jak dlouho kód platí', paragraphs: ['Výsledkem je potvrzení o přidělení codice fiscale, které může konzulát zaslat elektronicky jako PDF. Plastová karta se osobám žijícím v zahraničí běžně nevydává a pro koupi není podmínkou. Potvrzení předejte notáři nebo profesionálovi, který připravuje dokumentaci.', 'Kód nemá běžnou dobu platnosti. Pokud jste v Itálii dříve pracovali, studovali, dědili nebo řešili jiný úřední úkon, můžete jej už mít. Duplicita není řešením – nejprve nechte původní kód ověřit.'] },
      { title: 'Nejčastější chyby zahraničních kupujících', bullets: ['použití pouze kódu vypočteného online bez úředního přidělení', 'žádost na konzulátu, v jehož obvodu žadatel nebydlí', 'nepodepsaný nebo neúplný formulář AA4/8', 'odlišné jméno či místo narození v žádosti a v dokladu', 'žádost těsně před rogitem a spoléhání na pevnou lhůtu', 'vyřízení jen pro jednoho z více budoucích vlastníků'], note: 'Pokud kupují dva lidé, potřebuje vlastní codice fiscale každý z nich. U nezletilých vlastníků platí zvláštní dokumentační požadavky; ověřte je předem u příslušného úřadu nebo konzulátu.' },
      { title: 'Doporučené pořadí kroků před koupí', steps: [{t:'1. Ověřte, zda kód již nemáte',d:'Starší kód zůstává zpravidla platný. Nezakládejte druhou identitu.'},{t:'2. Podejte kompletní žádost',d:'Použijte oficiální AA4/8 a postup úřadu příslušného podle vašeho bydliště.'},{t:'3. Zkontrolujte potvrzení',d:'Porovnejte každý osobní údaj s dokladem, který použijete při podpisu.'},{t:'4. Předejte jej koordinátorovi a notáři',d:'Díky tomu lze správně připravit nabídku, předběžnou smlouvu a rogito.'},{t:'5. Uložte potvrzení',d:'Budete jej potřebovat i pro některé úkony po koupi.'}] }
    ],
    linksTitle: 'Související průvodci koupí', links: [{href:'/guides/notary',t:'Notář v Itálii',d:'Co notář kontroluje a jak se připravit na rogito.'},{href:'/guides/offerta-compromesso-registrazione',t:'Nabídka, compromesso a registrace',d:'Kdy se dokument stává závazným a co musí obsahovat.'},{href:'/guides/real-estate-purchase-system-italy',t:'Celý systém koupě krok za krokem',d:'Role, kontroly a návaznost jednotlivých fází.'}],
    sourcesTitle: 'Oficiální zdroje', sourcesIntro: 'Pravidla jsme ověřili podle oficiálních pokynů platných v době aktualizace článku. Před odesláním žádosti zkontrolujte aktuální verzi:',
    sources: [{href:'https://ambpraga.esteri.it/cs/servizi-consolari-e-visti/servizi-per-il-cittadino-italiano/codice-fiscale/',label:'Velvyslanectví Itálie v Praze – codice fiscale'},{href:'https://www.esteri.it/it/servizi-opportunita/italiani-all-estero/codice_fiscale/',label:'Ministerstvo zahraničních věcí Itálie – postup pro nerezidenty'},{href:'https://www1.agenziaentrate.gov.it/servizi/ecol/prenotazionionline.htm?last_step=0&reset_session=1&step_index=1',label:'Agenzia delle Entrate – rezervace schůzky na úřadě'}],
    closing: 'Potřebujete codice fiscale sladit s dokumenty ke koupi?', closingText:'Pomůžeme vám zkontrolovat pořadí kroků a koordinovat podklady s agenturou, technikem a notářem.', cta:'Kontaktovat nás'
  },
  it: {
    back:'Tutti gli articoli',category:'Acquistare casa in Italia',read:'10 minuti di lettura',title:'Codice fiscale per comprare casa in Italia: guida completa per stranieri',intro:'Il codice fiscale è uno dei primi documenti che un acquirente straniero dovrebbe procurarsi. Vediamo cos’è, perché serve per acquistare un immobile e come richiederlo correttamente dall’estero o direttamente in Italia.',imageAlt:'Tessera sanitaria italiana illustrativa con dati vuoti accanto ai documenti di acquisto di una casa',caption:'Richiedetelo per tempo: i dati del certificato devono coincidere con il documento usato nell’acquisto.',quickTitle:'In breve',quick:'Per completare normalmente il rogito e i successivi adempimenti fiscali serve un codice fiscale ufficialmente attribuito. Non è necessario per cercare casa, ma è prudente ottenerlo prima di firmare una proposta vincolante o un preliminare.',
    sections:[
      {title:'Cos’è il codice fiscale – e cosa non è',paragraphs:['È l’identificativo alfanumerico attribuito dall’Agenzia delle Entrate per identificare persone italiane e straniere nei rapporti con amministrazioni e soggetti privati. Per le persone fisiche è normalmente composto da 16 caratteri, ma conta l’attribuzione ufficiale, non il risultato di un calcolatore online.','Non è una partita IVA, un permesso di soggiorno o una prova di residenza fiscale italiana. Non coincide neppure con la tessera sanitaria: il codice può comparirvi, ma l’attribuzione non dà automaticamente diritto all’assistenza sanitaria italiana.'],bullets:['identifica l’acquirente negli atti e negli adempimenti fiscali','normalmente non ha scadenza','il cambio di residenza non lo modifica','ogni comproprietario deve avere il proprio codice']},
      {title:'Perché serve nell’acquisto immobiliare',paragraphs:['Notaio e amministrazioni lo usano per identificare le parti, liquidare e versare le imposte, registrare gli atti e gestire gli adempimenti connessi alla proprietà. Può essere richiesto anche per conto corrente, mutuo, utenze e altri rapporti successivi.','Non ogni visita o trattativa preliminare lo richiede e per alcuni atti privati esistono procedure particolari per non residenti. Per pianificare senza rischi, tuttavia, deve risultare correttamente attribuito prima dell’atto notarile.'],bullets:['proposta e preliminare: è opportuno averlo già','rogito notarile: è concretamente necessario','registrazione e imposte: collega atti e versamenti alla persona','dopo l’acquisto: serve in numerosi rapporti amministrativi']},
      {title:'I tre canali ufficiali per ottenerlo',paragraphs:['Le autorità italiane indicano tre modalità principali.'],steps:[{t:'1. Consolato competente per residenza',d:'Chi risiede nella Repubblica Ceca può seguire le istruzioni aggiornate dell’Ambasciata d’Italia a Praga, inviando modulo AA4/8 e allegati.'},{t:'2. Agenzia delle Entrate in Italia',d:'Durante un soggiorno in Italia si può presentare domanda a un ufficio territoriale con AA4/8, documento valido e motivazione.'},{t:'3. Persona delegata in Italia',d:'Una delega speciale consente a un incaricato di presentare la richiesta, con il proprio documento, la copia di quello del richiedente e la delega compilata.'}]},
      {title:'Domanda dalla Repubblica Ceca',paragraphs:['Il residente ceco deve attenersi alle istruzioni aggiornate della sezione consolare di Praga. Contatti e modalità operative possono cambiare.'],bullets:['modulo AA4/8 compilato e firmato con dati identici al documento','copia di passaporto o carta d’identità validi con fotografia; la patente non è accettata','prova della residenza nella Repubblica Ceca','motivazione chiara, ad esempio l’acquisto previsto di un immobile','allegati completi e perfettamente leggibili'],note:'L’Ambasciata avverte che le domande incomplete o di persone non residenti nella Repubblica Ceca vengono respinte e non garantisce un tempo fisso di lavorazione.'},
      {title:'Come compilare correttamente l’AA4/8',paragraphs:['Il modello va compilato in stampatello, firmato e completo dei dati obbligatori. Il non residente indica anche l’indirizzo estero e la motivazione. Nome, data e luogo di nascita devono coincidere con il documento allegato.','In caso di delega va compilata la relativa sezione. Un errore può emergere durante la preparazione dell’atto e rallentare l’operazione; il Consolato di Praga precisa che le correzioni di un codice già attribuito vanno gestite con l’Agenzia delle Entrate in Italia.'],bullets:['non copiare i dati da generatori non ufficiali','non richiedere un nuovo codice se ne possiedi già uno','verificare la corrispondenza con il documento destinato al notaio','conservare il certificato elettronico originale']},
      {title:'Cosa si riceve e quanto dura',paragraphs:['Il risultato è un certificato di attribuzione, che può essere inviato dal consolato in PDF. La tessera plastificata non viene normalmente rilasciata ai residenti all’estero e non è necessaria per acquistare.','Il codice non ha una normale scadenza. Chi ha già lavorato, studiato o svolto pratiche in Italia potrebbe possederlo: occorre verificare quello originario, non crearne un duplicato.']},
      {title:'Errori più frequenti',bullets:['usare un codice soltanto calcolato online','rivolgersi a un consolato non competente per residenza','inviare l’AA4/8 incompleto o non firmato','indicare dati diversi dal documento','presentare la domanda a ridosso del rogito','richiederlo per uno solo dei futuri comproprietari'],note:'Ogni acquirente deve avere il proprio codice. Per i minori sono previsti documenti specifici: verificate il caso con l’autorità competente.'},
      {title:'Ordine pratico consigliato',steps:[{t:'1. Verificare se esiste già',d:'Un vecchio codice resta normalmente valido: evitate duplicazioni.'},{t:'2. Presentare la domanda completa',d:'Usate AA4/8 e la procedura dell’ufficio competente.'},{t:'3. Controllare il certificato',d:'Confrontate ogni dato con il documento che userete al rogito.'},{t:'4. Trasmetterlo a coordinatore e notaio',d:'Permette di predisporre correttamente proposta, preliminare e atto.'},{t:'5. Conservarlo',d:'Servirà anche per diversi adempimenti successivi.'}]}
    ],linksTitle:'Guide collegate',links:[{href:'/guides/notary',t:'Il notaio in Italia',d:'Controlli e preparazione del rogito.'},{href:'/guides/offerta-compromesso-registrazione',t:'Proposta, compromesso e registrazione',d:'Quando gli impegni diventano vincolanti.'},{href:'/guides/real-estate-purchase-system-italy',t:'Il sistema di acquisto completo',d:'Ruoli, verifiche e fasi della compravendita.'}],sourcesTitle:'Fonti ufficiali',sourcesIntro:'Contenuto verificato sulle istruzioni ufficiali disponibili alla data di aggiornamento. Prima della domanda controllate sempre le indicazioni correnti:',sources:[{href:'https://ambpraga.esteri.it/cs/servizi-consolari-e-visti/servizi-per-il-cittadino-italiano/codice-fiscale/',label:'Ambasciata d’Italia a Praga – codice fiscale'},{href:'https://www.esteri.it/it/servizi-opportunita/italiani-all-estero/codice_fiscale/',label:'Ministero degli Affari Esteri – non residenti'},{href:'https://www1.agenziaentrate.gov.it/servizi/ecol/prenotazionionline.htm?last_step=0&reset_session=1&step_index=1',label:'Agenzia delle Entrate – prenota un appuntamento in ufficio'}],closing:'Vuoi coordinare il codice fiscale con i documenti di acquisto?',closingText:'Ti aiutiamo a ordinare i passaggi e a coordinare la pratica con agenzia, tecnico e notaio.',cta:'Contattaci'
  },
  en: {
    back:'All articles',category:'Buying property in Italy',read:'10 min read',title:'Italian tax code for buying property: a complete guide for foreign buyers',intro:'The Italian codice fiscale is one of the first documents a foreign buyer should obtain. This guide explains what it is, why it matters when buying a home, and how to request it correctly from abroad or in Italy.',imageAlt:'Illustrative Italian health card with blank details beside home-purchase documents',caption:'Apply early: the certificate details must exactly match the identity document used for the purchase.',quickTitle:'The short answer',quick:'An officially assigned codice fiscale is normally needed to complete the notarial deed and related tax formalities. You do not need it merely to search for a house, but obtaining it before a binding offer or preliminary contract avoids preventable delays.',
    sections:[
      {title:'What the codice fiscale is – and is not',paragraphs:['It is the alphanumeric identifier assigned by the Italian Revenue Agency to identify Italian and foreign individuals in dealings with public authorities and private entities. For individuals it normally contains 16 characters, but official assignment matters—not an online calculator result.','It is not a VAT number, residence permit, or proof of Italian tax residence. Nor is it the same as a health card: the number may appear on one, but assignment alone does not create an entitlement to Italian healthcare.'],bullets:['identifies the buyer in deeds and tax filings','normally has no expiry date','a change of address does not change it','every co-buyer needs an individual code']},
      {title:'Why a property buyer needs it',paragraphs:['The notary and authorities use it to identify the parties, assess and pay taxes, register deeds, and manage ownership-related formalities. It may also be requested for banking, mortgages, utilities, and later administrative matters.','Not every viewing or early negotiation requires it, and special procedures can apply to certain private instruments involving non-residents. For safe planning, however, the code should be correctly assigned before the final notarial deed.'],bullets:['offer and preliminary contract: best obtained beforehand','notarial deed: effectively required','registration and taxes: links deeds and payments to the buyer','after completion: used in many administrative relationships']},
      {title:'Three official ways to obtain it',paragraphs:['Italian authorities identify three main routes.'],steps:[{t:'1. The consulate responsible for your residence',d:'Residents of the Czech Republic can follow the current instructions of the Italian Embassy in Prague and send form AA4/8 with the required attachments.'},{t:'2. An Italian Revenue Agency office',d:'While in Italy, apply at a territorial office with form AA4/8, valid ID, and the reason for the request.'},{t:'3. An authorised representative in Italy',d:'A special authorisation allows another person to submit the request with their ID, a copy of yours, and the completed delegation.'}]},
      {title:'Applying from the Czech Republic',paragraphs:['Czech residents should follow the Prague consular section’s latest instructions, as contacts and operating rules can change.'],bullets:['completed and signed AA4/8 with data matching the ID exactly','copy of a valid passport or identity card showing a photograph; a driving licence is not accepted','proof of residence in the Czech Republic','clear reason, such as a planned Italian property purchase','complete and legible attachments'],note:'The Embassy says incomplete applications and applications from non-Czech residents will be rejected. It does not promise a fixed processing time, so apply well ahead.'},
      {title:'Completing form AA4/8 correctly',paragraphs:['Complete the form in block capitals, sign it, and include every mandatory field. Non-residents also enter their foreign address and the reason for applying. Name, birth date, and birthplace must match the attached identity document.','For representation, complete and sign the delegation section. Data errors can surface during deed preparation and delay completion; the Prague Consulate says corrections to an assigned code must be handled with the Revenue Agency in Italy.'],bullets:['do not copy data from an unofficial generator','do not request another code if one was previously assigned','match the ID that will be used before the notary','retain the original electronic certificate']},
      {title:'What you receive and how long it lasts',paragraphs:['You receive an assignment certificate, which the consulate may deliver electronically as a PDF. A plastic card is not normally issued to residents abroad and is not required for the purchase.','The code does not normally expire. If you previously worked, studied, inherited, or completed formalities in Italy, you may already have one: verify the original rather than creating a duplicate.']},
      {title:'Common foreign-buyer mistakes',bullets:['using only a code produced by an online calculator','applying to a consulate that is not competent for the place of residence','submitting an unsigned or incomplete AA4/8','using identity data that differ from the ID','applying immediately before the deed and assuming a fixed deadline','obtaining it for only one of several future owners'],note:'Each buyer needs their own code. Specific documents apply to minors; check the case with the competent authority in advance.'},
      {title:'Recommended practical sequence',steps:[{t:'1. Check whether you already have one',d:'An older code normally remains valid; avoid duplicate identities.'},{t:'2. Submit a complete application',d:'Use the official AA4/8 and the procedure of the competent office.'},{t:'3. Check the certificate',d:'Compare every detail with the ID intended for completion.'},{t:'4. Send it to your coordinator and notary',d:'This allows the offer, preliminary contract, and deed to be prepared correctly.'},{t:'5. Keep the certificate',d:'It will also be useful for later formalities.'}]}
    ],linksTitle:'Related buying guides',links:[{href:'/guides/notary',t:'The Italian notary',d:'Checks and preparation for the deed.'},{href:'/guides/offerta-compromesso-registrazione',t:'Offer, preliminary contract, and registration',d:'When commitments become binding.'},{href:'/guides/real-estate-purchase-system-italy',t:'The complete purchase system',d:'Roles, checks, and transaction stages.'}],sourcesTitle:'Official sources',sourcesIntro:'This content was checked against official guidance available on the update date. Always review the current instructions before applying:',sources:[{href:'https://ambpraga.esteri.it/cs/servizi-consolari-e-visti/servizi-per-il-cittadino-italiano/codice-fiscale/',label:'Italian Embassy in Prague – codice fiscale'},{href:'https://www.esteri.it/it/servizi-opportunita/italiani-all-estero/codice_fiscale/',label:'Italian Ministry of Foreign Affairs – non-residents'},{href:'https://www1.agenziaentrate.gov.it/servizi/ecol/prenotazionionline.htm?last_step=0&reset_session=1&step_index=1',label:'Italian Revenue Agency – book an office appointment'}],closing:'Need to coordinate your tax code with the purchase documents?',closingText:'We can help organise the sequence and coordinate the file with the agency, surveyor, and notary.',cta:'Contact us'
  }
}

function ArticleSection({ section }) {
  return <Card className="bg-white/95 shadow-sm"><CardHeader><CardTitle className="text-2xl text-slate-900">{section.title}</CardTitle></CardHeader><CardContent className="space-y-4">
    {section.paragraphs?.map((p) => <p key={p} className="leading-7 text-slate-700">{p}</p>)}
    {section.bullets && <ul className="space-y-3">{section.bullets.map((item) => <li key={item} className="flex gap-3 text-slate-700"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-emerald-600"/><span>{item}</span></li>)}</ul>}
    {section.steps && <div className="space-y-4">{section.steps.map((step) => <div key={step.t} className="rounded-xl border border-slate-200 bg-slate-50 p-4"><h3 className="mb-1 font-semibold text-slate-900">{step.t}</h3><p className="leading-7 text-slate-700">{step.d}</p></div>)}</div>}
    {section.note && <div className="flex gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 text-amber-950"><ShieldAlert className="mt-0.5 h-5 w-5 shrink-0"/><p className="leading-7">{section.note}</p></div>}
  </CardContent></Card>
}

export default function CodiceFiscaleGuidePage() {
  const [language, setLanguage] = useState('cs')
  useEffect(() => { const saved=localStorage.getItem('preferred-language'); if (CONTENT[saved]) setLanguage(saved); const handler=(e)=>CONTENT[e.detail]&&setLanguage(e.detail); window.addEventListener('languageChange',handler); return()=>window.removeEventListener('languageChange',handler)},[])
  const c=CONTENT[language]||CONTENT.cs
  return <div className="min-h-screen bg-gradient-to-br from-[#f7f4ed] via-amber-50/20 to-slate-50"><Navigation/><main className="pb-16 pt-28 md:pb-24"><article className="container mx-auto px-6" style={{maxWidth:'1200px'}}><div className="mx-auto max-w-3xl">
    <Button asChild variant="outline" className="mb-6"><Link href="/blog"><ArrowLeft className="mr-2 h-4 w-4"/>{c.back}</Link></Button>
    <div className="mb-8"><div className="mb-4 flex flex-wrap gap-3 text-sm font-medium text-slate-600"><span className="rounded-full bg-slate-100 px-3 py-1">{c.category}</span><span className="px-1 py-1">{c.read}</span></div><h1 className="mb-6 text-slate-900">{c.title}</h1><p className="text-lg leading-8 text-slate-700">{c.intro}</p></div>
    <figure className="mb-8 overflow-hidden rounded-2xl border border-slate-200 bg-white"><Image src="/articles/codice-fiscale-acquisto-casa-italia.png" alt={c.imageAlt} width={1536} height={1024} priority className="h-auto w-full"/><figcaption className="px-5 py-3 text-sm text-slate-600">{c.caption}</figcaption></figure>
    <Card className="mb-8 border-emerald-200 bg-emerald-50"><CardContent className="p-6"><h2 className="mb-3 flex items-center text-xl font-semibold text-emerald-950"><BadgeCheck className="mr-2 h-6 w-6"/>{c.quickTitle}</h2><p className="leading-7 text-emerald-950">{c.quick}</p></CardContent></Card>
    <div className="space-y-8">{c.sections.map((section)=><ArticleSection key={section.title} section={section}/>)}</div>
    <section className="mt-10"><h2 className="mb-5 text-2xl font-bold text-slate-900">{c.linksTitle}</h2><div className="grid gap-4 md:grid-cols-3">{c.links.map((item)=><Link key={item.href} href={item.href} className="rounded-xl border border-slate-200 bg-white p-5 transition hover:-translate-y-0.5 hover:shadow-md"><KeyRound className="mb-3 h-5 w-5 text-emerald-700"/><h3 className="mb-2 font-semibold text-slate-900">{item.t}</h3><p className="text-sm leading-6 text-slate-600">{item.d}</p></Link>)}</div></section>
    <section className="mt-10 rounded-2xl border border-slate-200 bg-white p-6"><h2 className="mb-3 flex items-center text-2xl font-bold text-slate-900"><Landmark className="mr-3 h-6 w-6"/>{c.sourcesTitle}</h2><p className="mb-4 leading-7 text-slate-700">{c.sourcesIntro}</p><ul className="space-y-3">{c.sources.map((s)=><li key={s.href}><a href={s.href} target="_blank" rel="noopener noreferrer" className="inline-flex items-start gap-2 font-medium text-emerald-800 hover:underline">{s.label}<ExternalLink className="mt-1 h-4 w-4 shrink-0"/></a></li>)}</ul></section>
    <section className="my-10 rounded-2xl bg-slate-900 p-7 text-white"><Building2 className="mb-4 h-8 w-8 text-emerald-400"/><h2 className="mb-3 text-2xl font-bold">{c.closing}</h2><p className="mb-5 leading-7 text-slate-200">{c.closingText}</p><Button asChild className="bg-emerald-600 hover:bg-emerald-700"><Link href="/contact"><FileText className="mr-2 h-4 w-4"/>{c.cta}</Link></Button></section>
    <InformationalDisclaimer language={language}/>
  </div></article></main><PropertySlider language={language}/><Footer/></div>
}
